name: rpi5-quant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.0
  - matplotlib=3.8.2
  - scipy=1.12.0
  - pillow=10.4.0
  - pip
  - pip:
    - onnxruntime==1.18.0
    - psutil==5.9.8
